// Miguel Gargallo 2022 (c) All Rights Reserved.
export const WORDS = [
  'aaaaa',
  'barna',
  'boobs',
  'booty',
  'coños',
  'culos',
  'dicks',
  'gatos',
  'grito',
  'lesbi',
  'lucas',
  'music',
  'ortos',
  'pedos',
  'pedro',
  'penes',
  'penis',
  'pride',
  'prime',
  'pussy',
  'sonia',
  'tetis',
  'tonta',
  // Combinaciones que faltan by Miguel Gargallo
  'sinpa',
  'sofia',
  // Combinaciones ganadoras by Miguel Gargallo
  'turia',
  'celos',
  'coles',
  'judia',
  'murio',
  'ebola',
  'covid',
  // Combinaciones de la hostia by Miguel Gargallo
  'ellie',
  'riley',
  'jesse',
  'chloe',
  'croft',
  // Famosos by Miguel Gargallo
  'nathy',
  'saoko',
  // Disney+ by Miguel Gargallo
  'simba',
  'mulan',
  'mulan',
  // Cosas random válidas by Miguel Gargallo
  'belen',
]